### ISSUE TITLE
process create whitelist editor eval errors on add/remove actions when input values have special characters

### ISSUE THREAD

**Issue by dstaulcu** [olafhartong/ThreatHunting#101]
this issue happens in cases where inputs have special characters such as quotes.  for me this occurs most often in command_line oriented inputs.

the [simple xml reference](https://docs.splunk.com/Documentation/Splunk/9.0.1/Viz/PanelreferenceforSimplifiedXML) describes an option to overcome this sort of problem with use of the "|s$" token filter which transforms the value of a field to string.

credit goes to slack user daljeanis who pointed this feature out to me in the dashboards_simple_xml channel.

**Comment by dstaulcu** [comment]
`<form version="1.1">
  <label>Process Create whitelist editor</label>
  <fieldset submitButton="true" autoRun="false">
    <input type="dropdown" token="mitre_technique_id" id="mitre_technique_id">
      <label>mitre_technique_id</label>
      <search>
        <query>| rest /servicesNS/-/ThreatHunting/saved/searches 
| fields title, search
| eval search=urldecode(search)
| regex search="(?i)mitre_technique_id=\"T\d+\""
| rex field=search "mitre_technique_id=\"(?&lt;id&gt;T\d+)\"" 
| stats dc(id) AS Searches by id 
| sort id 
| table id</query>
      </search>
      <fieldForLabel>id</fieldForLabel>
      <fieldForValue>id</fieldForValue>
      <choice value="*">All (*)</choice>
    </input>
    <input type="text" token="host_fqdn">
      <label>host_fqdn</label>
      <default></default>
    </input>
    <input type="text" token="user_name">
      <label>user_name</label>
      <default></default>
    </input>
    <input type="text" token="process_path">
      <label>process_path</label>
      <default></default>
    </input>
    <input type="text" token="process_parent_path">
      <label>process_parent_path</label>
      <default></default>
    </input>
    <input type="text" token="process_command_line">
      <label>process_command_line</label>
      <default>*</default>
      <initialValue>*</initialValue>
    </input>
    <input type="text" token="hash_sha256">
      <label>hash_sha256</label>
      <default></default>
    </input>
    <input type="text" token="input_reason">
      <label>Reason</label>
      <default>CHANGEME</default>
    </input>
    <input type="radio" token="input_mode">
      <label>Mode</label>
      <choice value="add">Add</choice>
      <choice value="delete">Remove</choice>
      <default>add</default>
    </input>
  </fieldset>
  <row>
    <panel>
      <table>
        <title>Recent Entries</title>
        <search>
          <query>| makeresults 
| eval input_host_fqdn = COALESCE(if(trim($host_fqdn|s$)="", "*", trim($host_fqdn|s$)), "*") 
| eval input_user_name = COALESCE(if(trim($user_name|s$)="", "*", trim($user_name|s$)), "*") 
| eval input_mitre_technique_id = COALESCE(if(trim($mitre_technique_id|s$)="", "*", trim($mitre_technique_id|s$)), "*") 
| eval input_process_command_line = COALESCE(if(trim($process_command_line|s$)="", "*", trim($process_command_line|s$)), "*") 
| eval input_process_path = COALESCE(if(trim($process_path|s$)="", "*", trim($process_path|s$)), "*") 
| eval input_process_parent_path = COALESCE(if(trim($process_parent_path|s$)="", "*", trim($process_parent_path|s$)), "*") 
| eval input_hash_sha256 = COALESCE(if(trim($hash_sha256|s$)="", "*", trim($hash_sha256|s$)), "*") 

| eval host_fqdn = input_host_fqdn 
| eval user_name = input_user_name 
| eval mitre_technique_id = input_mitre_technique_id 
| eval process_command_line = input_process_command_line
| eval process_path = input_process_path 
| eval process_parent_path = input_process_parent_path 
| eval hash_sha256 = input_hash_sha256 
| eval reason = trim($input_reason|s$)
| eval added_date = strftime(now(), "%Y-%m-%d") 
| eval contact = ("$env:user$") 
| table * 
| fields - _raw _time 
| where reason!="CHANGEME" 

| inputlookup append=t threathunting_process_create_whitelist.csv 
| sort -added_date 
| dedup host_fqdn, user_name, mitre_technique_id, process_path process_parent_path process_command_line hash_sha256 

| eval mode = "$input_mode$" 
| eval delete=if(mode="delete" and mitre_technique_id=input_mitre_technique_id and host_fqdn=input_host_fqdn and user_name=input_user_name and process_command_line=input_process_command_line and process_path=input_process_path and process_parent_path=input_process_parent_path and hash_sha256=input_hash_sha256, "yes", "no") 
| where delete="no" 
| fields - delete mode 
| fields - input_host_fqdn input_user_name input_mitre_technique_id input_process_command_line input_process_path input_process_parent_path input_hash_sha256
| outputlookup threathunting_process_create_whitelist.csv 
| fields added_date contact mitre_technique_id reason host_fqdn user_name process_path process_parent_path process_command_line hash_sha256</query>
          <earliest>0</earliest>
        </search>
        <option name="count">5</option>
        <option name="dataOverlayMode">none</option>
        <option name="drilldown">none</option>
        <option name="rowNumbers">false</option>
        <option name="wrap">true</option>
      </table>
    </panel>
  </row>
  <row>
    <panel>
      <table>
        <title>Current Entries</title>
        <search>
          <query>| inputlookup threathunting_process_create_whitelist.csv | sort -added_date | fields added_date contact mitre_technique_id reason host_fqdn user_name process_path process_parent_path process_command_line hash_sha256
</query>
          <earliest>0</earliest>
        </search>
        <option name="count">100</option>
        <option name="dataOverlayMode">none</option>
        <option name="drilldown">none</option>
        <option name="rowNumbers">false</option>
        <option name="wrap">true</option>
      </table>
    </panel>
  </row>
</form>`

**Comment by dstaulcu** [comment]
shoot -- my fork of your repo is too far ahead to issue a pull request. 
here is the code block that needs to change within process_create_whitelist.xml
```
| eval input_host_fqdn = COALESCE(if(trim($host_fqdn|s$)="", "*", trim($host_fqdn|s$)), "*") 
| eval input_user_name = COALESCE(if(trim($user_name|s$)="", "*", trim($user_name|s$)), "*") 
| eval input_mitre_technique_id = COALESCE(if(trim($mitre_technique_id|s$)="", "*", trim($mitre_technique_id|s$)), "*") 
| eval input_process_command_line = COALESCE(if(trim($process_command_line|s$)="", "*", trim($process_command_line|s$)), "*") 
| eval input_process_path = COALESCE(if(trim($process_path|s$)="", "*", trim($process_path|s$)), "*") 
| eval input_process_parent_path = COALESCE(if(trim($process_parent_path|s$)="", "*", trim($process_parent_path|s$)), "*") 
| eval input_hash_sha256 = COALESCE(if(trim($hash_sha256|s$)="", "*", trim($hash_sha256|s$)), "*") 
```

**Comment by olafhartong** [comment]
again thanks for those! appreciate the support! added them
