### ISSUE TITLE
change "sourcetype" to "source" for Win Event Logs in the macros

### ISSUE THREAD

**Issue by bmk666** [olafhartong/ThreatHunting#12]
For me i have to change all the macros:

from
**index=INDEX sourcetype="WinEventLog:Application"**
to
**index=INDEX source="WinEventLog:Application"**

because only sysmon have its own sourcetype:
**"XmlWinEventLog:Microsoft-Windows-Sysmon/Operational"**

All other windows logs have sourcetype:
**"xmlwineventlog"**

so i have to use **"source=WinEventLog:System"**, **"source=WinEventLog:Application"**,....

BR,
BMK

**Comment by jamesarmitage** [comment]
Note: this only applies if you are using the 5.x release of TA-Windows for Splunk.  The 4.x release still uses sourcetype: [https://docs.splunk.com/Documentation/WindowsAddOn/5.0.1/User/Upgrade#WinEventLog_extraction_changes](https://docs.splunk.com/Documentation/WindowsAddOn/5.0.1/User/Upgrade#WinEventLog_extraction_changes)

**Comment by agiallombardo** [comment]
@jamesarmitage - v4 does still use sourcetype, but source is both v4 & v5 compatible

**Comment by olafhartong** [comment]
this has been addressed in the macro
