### ISSUE TITLE
Whitelists not working on "Threat Hunting trigger overview"

### ISSUE THREAD

**Issue by bmk666** [olafhartong/ThreatHunting#13]
"Threat Hunting trigger overview" shows all past triggers, even if i add some stuff to the white lists. 
White lists are only working in drilldowns.

It will be great if all whitelisted events not shown on the "Threat Hunting trigger overview" page!

BR,
Sascha

**Comment by bmk666** [comment]
Hmm now its working....

**Comment by bmk666** [comment]
Got it, you have to add:

**| `registry_whitelist` | `process_create_whitelist`**

to every search on the "Threat Hunting trigger overview" Dashboard.

BR,
Sascha

**Comment by olafhartong** [comment]
I've been considering filtering the overview, need to do some performance tests to see if the whitelisting will not impact the search speed too much

**Comment by olafhartong** [comment]
added to latest commit
