### ISSUE TITLE
Not Getting Logs

### ISSUE THREAD

**Issue by jsecurity101** [olafhartong/ThreatHunting#14]
I recently have done a clean build of Chris Long's Detection Lab, where your updated tool is implemented (used it before great tool, thank you for your work on it) I have attached a screenshot of the Dashboard and the macros.conf file. Thank you in advance!
Dashboard:
![image](https://user-images.githubusercontent.com/29631806/53987038-60f70280-40e5-11e9-8556-20b90200296a.png)
Top of macro.conf:
![image](https://user-images.githubusercontent.com/29631806/53987224-04481780-40e6-11e9-8939-88063e7542e6.png)

**Comment by jsecurity101** [comment]
Hey @olafhartong I found the issue. It was an indexes issue. I will close the ticket.

**Comment by hermitsy** [comment]
> Hey @olafhartong I found the issue. It was an indexes issue. I will close the ticket.

@jsecurity101 - Would you mind sharing your fix please?
