### ISSUE TITLE
Drilldown not working with more than one MITRE Category

### ISSUE THREAD

**Issue by bmk666** [olafhartong/ThreatHunting#15]
When i click on the overview page in the table "Top triggered techniques" one entry with more than one "mitre_category" the drilldown will not work!

For example:

T1088 | Bypass User Account Control | Privilege_Escalation,Defense_Evasion

In the drilldown the "MITRE Cagegory" field is filled with "Privilege_Escalation,Defense_Evasion",
but you can only search for each one, not as comma separated.

BR,

BMK

**Comment by olafhartong** [comment]
I'm working on some improvements in this area, thanks for all Issues you've been filing, I appreciate you taking the time to do so!

**Comment by olafhartong** [comment]
this has been fixed in the latest commit
