### ISSUE TITLE
Registry whitelist editor not working with "registry_key_details" field with "null" value

### ISSUE THREAD

**Issue by bmk666** [olafhartong/ThreatHunting#16]
Many of whitelisted registry access have no "registry_key_details" value (value null) so it is not working with "*", so null values must be possible.

I used the Lookup Editor to add the registry exclusions with null value and it is working. But when i used your whitelist editor after i added some "null" values, all my entrys with "null" are deleted 
after saving!

BR,
BMK

**Comment by olafhartong** [comment]
Are you working with version 1.1 or 1.2? This should be addressed in 1.2 already

**Comment by olafhartong** [comment]
this is fixed in 1.2
