### ISSUE TITLE
Computer drilldown returns no events occasionally

### ISSUE THREAD

**Issue by 70bb3** [olafhartong/ThreatHunting#25]
On the overview page and when clicking on a row in the pane "Top triggered host_fqdns" the Computer Drilldown appears. The graph seems to work fine, but the "related raw logs" pane is empty some times. It seems to be due to the query is limited to show sysmon events only, not including regular windows events, which the dashboard in the previous view is also based on.

**Comment by olafhartong** [comment]
Thanks for letting me know! I'll take care of this.

**Comment by olafhartong** [comment]
Revised the dashboard in the current version. Could not reproduce your issue. Can you check whether it’s working as expected?
