### ISSUE TITLE
Bug in Process Create whitelist editor

### ISSUE THREAD

**Issue by 70bb3** [olafhartong/ThreatHunting#26]
In the Process Create whitelist editor, when leaving the field "process_command_line" empty it will not automatically be filled with a "*". Not sure about the impact of this, but it might result in unexpected behaviour.

**Comment by olafhartong** [comment]
Thanks for letting me know! I'll take care of this. Not having data in the field might give undesired results

**Comment by olafhartong** [comment]
There was something why I didn't do this by default because it was causing me some issues, I'll look into it again to see whether I can fix it

**Comment by olafhartong** [comment]
I think I can solve it by adding a default and initial value, unless someone removes it, but can't deal with it in the same fashion otherwise some commands with special characters will not be added to the whitelist
