### ISSUE TITLE
Update Splunkbase version

### ISSUE THREAD

**Issue by deadstick6** [olafhartong/ThreatHunting#27]
Hey,

Can the latest version please be submitted to Splunkbase ? Trying to get this installed on SplunkCloud and Support will only accept an app for vetting if its submitted via Splunkbase (tried giving them the github link, no joy). 

Cheers,

**Comment by olafhartong** [comment]
Will do that soon, the latest release will be public during BlackHat

**Comment by olafhartong** [comment]
The latest version is available on SplunkBase. The appinspect fails on 2 things, one I'll adjust the other one is the lookups. I deliberately do not provide them as they are specific to the environment it's installed on. If I would provide them it would override them on upgrade, which is not good :D
