### ISSUE TITLE
Question - Index not populating

### ISSUE THREAD

**Issue by biz0b** [olafhartong/ThreatHunting#31]
I'm having an problem that I can't figure out, and I'm at wit's end over it now.

I've got a clean install of Splunk, and I've installed the ThreatHunting app.  Created the ThreatHunting index.  Installed sysmon and the universal forwarder on a system.  Changed the macro to reflect the name of the sysmon index.  Data is being sent to the sysmon index.  But no data is being ingested to the ThreatHunting index.

What else could I be doing wrong?  Is there a log file that might help me figure out what the issue is?  I installed everything a few months ago to test and it was pretty flawless.  This time, not so much and I'm not sure why.

**Comment by antaji** [comment]
Not sure if this is the right answer, but what I did was edit or add an inputs.conf file in C:\Program Files\Splunkforwader\etc\system\local.  And added the following:

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = false
renderXml = false
sourcetype = WinEventLog:Microsoft-Windows-Sysmon/Operational
index = threathunting

Then restart splunk on both forwarder and indexer.
I did the same on the indexer and my index starting getting logs.

**Comment by biz0b** [comment]
I think it has more to do with the saved searches that are supposed to be populated the threathunting index.  When the searches run, I get the error "Could not load lookup=LOOKUP-eventcode" and the search log shows these errors:
LookupDataProvider - Could not find all of the specified destination fields in the lookup table.
AutoLookupDriver - Could not load lookup='LOOKUP-eventcode' reason='Error in 'lookup' command: Could not find all of the specified destination fields in the lookup table.'

Similar issue posted here but the fix here is already applied in the new version of the app and I'm still having the problem:  https://answers.splunk.com/answers/725649/unable-to-find-lookup-eventcode.html

**Comment by biz0b** [comment]
I think I got it worked out, but I'm honestly not entirely sure I understand why the fix worked.
In input.conf on the SplunkUniversalForwarder of the Windows host, I had the line
renderXml = true
I changed that to false, and it works.  I can't say I understand why though, but I'll close this "issue"
