### ISSUE TITLE
threathunting Summary Index Macro

### ISSUE THREAD

**Issue by billmurrin** [olafhartong/ThreatHunting#37]
Olaf,

Our team uses a custom name for the `threathunting` index. With that in mind, we realized how you used the `sysmon` macro and thought it might a great idea if you also included a `threathunting` macro to help define the `threathunting` summary index. If you like that idea, I don't mind helping out doing some of the lifting to make that work.

**Comment by OutpostSecurity** [comment]
I can grab this and work n it throughout this week.
