### ISSUE TITLE
Could not load lookup=LOOKUP-eventcode

### ISSUE THREAD

**Issue by francescouk** [olafhartong/ThreatHunting#43]
Hello there, I´m trying to install threathunting app, but for some reason I could not find out why is throwing this error:

![Threat Hunting trigger overview](https://user-images.githubusercontent.com/1994892/70904076-468c7680-1fdf-11ea-9845-99cb139f56ff.png)

Thanks in advance for yout attention.

**Comment by ericm272** [comment]
I'm experiencing the same thing. It appears to be a conflict with the Windows Defender TA and/or the Sysmon TA - both of those also use eventcode.csv and LOOKUP-eventcode. Here is some output from job inspector:

01-27-2020 00:21:55.214 WARN  CalcFieldProcessor - Invalid eval expression for 'EVAL-target_process_name' in stanza [WinEventLog:Microsoft-Windows-Sysmon/Operational]: The operator at ',replace(TargetImage,"(.*\\\)(?=.*(\.\w*)$|(\w+)$)",""),1==1,"")' is invalid.
01-27-2020 00:21:55.215 WARN  CalcFieldProcessor - Invalid eval expression for 'EVAL-Feature_Name' in stanza [XmlWinEventLog:Microsoft-Windows-Windows Defender/Operational]: The expression is malformed. Expected ).
.........
01-27-2020 00:21:55.249 ERROR LookupDataProvider - Could not find all of the specified destination fields in the lookup table.
01-27-2020 00:21:55.249 ERROR AutoLookupDriver - Could not load lookup='LOOKUP-eventcode' reason='Error in 'lookup' command: Could not find all of the specified destination fields in the lookup table.'

**Comment by sickwell** [comment]
I have the same issue. Looks like conflict with eventcode.csv. Is there any planned update?

**Comment by lasdem** [comment]
I have the same issue.

**Comment by akjhhauyo956dhhv05** [comment]
same issue

**Comment by linuxpakistan** [comment]
Hello Everyone,

If you are using TA-microsoft-sysmon then you need to edit your $SPLUNKHOME/etc/apps/TA-microsoft-sysmon/default/props.conf

Comment out the line

**LOOKUP-eventcode = eventcode EventCode OUTPUTNEW EventDescription EventDescription AS signature**

Restart the Splunk and everything will be fine.

Thank you.

**Comment by olafhartong** [comment]
I just fixed it in the last pushes. Sorry for the delay

**Comment by hermitsy** [comment]
Could someone please describe how do we install the latest fixes/code, since Splunkbase app has not been updated since mid 2019.
