### ISSUE TITLE
event_description not showing in summary index

### ISSUE THREAD

**Issue by kpaxindustries** [olafhartong/ThreatHunting#5]
Hi there.
I've got the app up and running and think I've got it configured correctly. There is data in the threathunting index, but none of the data contains the event_description field, so the MITRE dashboard doesn't work.

If I run the saved search's search manually, then the event_description is there. I'm just stuck as to why it doesn't appear in the summary index, when the saved searches run every 15 mins

Any ideas? What info would you need from me to help?

Regards

P.S. Great app, keep up the work

**Comment by kpaxindustries** [comment]
Never mind. Turns out that when I first installed the app, the eventcode lookup wasn't there, so I created it myself, but the permissions where too tight, so the saved search couldn't use it. all working now

**Comment by Kirtar22** [comment]
Hi [kpaxindustries], 

I am also trying to use this App but not working. Can you please help? I have ingested Sysmon data in to "windows" index and all the pre-requisites apps are installed. macros have been updated with correct sourcetype for Sysmon data/query.  Copied all the lookups in the "lookups" folder of the App. However, MITRE dashboard is not getting populated. Threathunting index does not  have any data. 

any idea? any lead would be helpful. Thanks

**Comment by kpaxindustries** [comment]
First thing to check, is whether your macros are working. So open up the app and on the search tab, simply search for ``` `sysmon` ``` . If you get data back, then the macros are working as expected, if not, check props.conf again to make sure index and sourcetype are correct. I've seen some people have issues where the sourcetype for sysmon events they collect, doesn't have the XML letters at the beginning of it.

The threathunting index is populated by a number of saved searches that are run every 15 mins. If you take a look in splunk at the reports for the Threathunting app, you should see all these searches. You can then open them in search to see if they are working or not

**Comment by Kirtar22** [comment]
Yeah, it was the **sourcetype**. I figured it out after posting it here. I deleted XML part in "macros" & props.conf and data started flowing in the dashboard. Thanks for your help. appreciate your prompt reply.

**Comment by bmk666** [comment]
For me i have to change all the macros:

from
**index=INDEX sourcetype="WinEventLog:Application"**
to
**index=INDEX source="WinEventLog:Application"**

because only sysmon have its own sourcetype: 
**"XmlWinEventLog:Microsoft-Windows-Sysmon/Operational"**

All other windows logs have sourcetype:
**"xmlwineventlog"**

so i have to use **"source=WinEventLog:System"**, **"source=WinEventLog:Application"**,....

BR,
BMK

**Comment by olafhartong** [comment]
I've made a task to fix this
