### ISSUE TITLE
Could not load lookup=LOOKUP-sysmoneventcode

### ISSUE THREAD

**Issue by Moofeng** [olafhartong/ThreatHunting#54]
![image](https://user-images.githubusercontent.com/36625561/88242971-76140780-ccc1-11ea-8573-b96052b2d526.png)

**Comment by Moofeng** [comment]
I suggest we set up a discussion group

**Comment by sebastiendamaye** [comment]
In the ./lookups folder, create a symbolic link to sysmoneventcode.csv that points to sysmoneventcodes.csv and restart Splunk. Or fix the typo directly in ./default/props.conf

**Comment by olafhartong** [comment]
Thanks for pointing this out, it has been adjusted in the latest commits
