### ISSUE TITLE
Incorrect reference to sysmoneventcodes.csv in default/props.conf

### ISSUE THREAD

**Issue by sebastiendamaye** [olafhartong/ThreatHunting#56]
The file ./default/props.conf is incorrectly referencing sysmoneventcodes.csv (trailing "s" is missing):

`LOOKUP-sysmoneventcode = sysmoneventcode.csv EventCode OUTPUTNEW event_description
`
Instead of:

`LOOKUP-sysmoneventcode = sysmoneventcodes.csv EventCode OUTPUTNEW event_description`

**Comment by akjhhauyo956dhhv05** [comment]
while you wait for a new version to fix this, use this workaround:

cd /opt/splunk/etc/shcluster/apps/ThreatHunting/default && cp default/props.conf default/props.conf.OLD && vi default/props.conf 
press esc and enter the following to replace:
%s/sysmoneventcode.csv/sysmoneventcodes.csv/g

**Comment by olafhartong** [comment]
Thanks for pointing this out, it has been adjusted in the latest commits

**Comment by bchris21** [comment]
Is it the same with line 277?
`LOOKUP-sysmoneventcode = sysmoneventcodes.csv EventCode OUTPUTNEW event_description`

Is the trailing "s" missing from LOOKUP-sysmoneventcode  ?
