### ISSUE TITLE
Update required apps

### ISSUE THREAD

**Issue by Karma1331** [olafhartong/ThreatHunting#58]
The Link Analysis App is needed now, may want to add that to the docs. Thanks for the great app, modular and all else that goes with it!

**Comment by willmerae** [comment]
2 apps on Splunk Base match that name
- [Link Analysis App For Splunk](https://splunkbase.splunk.com/app/4676/)
- [Sigbay Link Analysis](https://splunkbase.splunk.com/app/5126/)

Link Analysis App For Splunk seems the most likely, based on it having more downloads.
