### ISSUE TITLE
Not Issue, Difficulties in up& running 

### ISSUE THREAD

**Issue by Kirtar22** [olafhartong/ThreatHunting#6]
Hi Olaf, 
 I have ingested Sysmon data in to "windows" index and all the pre-requisites apps are installed. macros have been updated with correct sourcetype for Sysmon data/query. Copied all the lookups in the "lookups" folder of the App. However, MITRE dashboard is not getting populated. Threathunting index does not have any data. any idea? any lead would be helpful. Thanks

**Comment by Kirtar22** [comment]
Nevermind ! it was the **sourcetype**. I figured it out after posting it here. I deleted XML part in "macros" & props.conf and data started flowing in the dashboard.  Thanks. Closing the Issue.

**Comment by jsecurity101** [comment]
Hi @Kirtar22 is there anyway you can show me y our macros,conf and props.conf? I believe I am having the same issue as you.

**Comment by Kirtar22** [comment]
Hi @jsecurity101 - Sure. Share your email id. will share over email. Thanks

**Comment by jsecurity101** [comment]
Hi @Kirtar22 I figured out the issue. Thank you for your help though!

**Comment by sulaimanbale** [comment]
Hi do you mind sharing it with me ? i am unable to get it to work.
