### ISSUE TITLE
Eval command failing in props.conf 

### ISSUE THREAD

**Issue by Suirand1** [olafhartong/ThreatHunting#60]
I have ThreatHunting 1.4.4 with TA-microsoft-sysmon 10.6.2. For some reason APP searches always return 0 events. After deeper inspection I figured out that problem is with field names used in searches. It looks like EVAL command field names are not applied as stated in props.conf.
For example when I run search:
```
`sysmon` EventCode=1                       #  I get all values with sysmon EventID=1
```          
```
`sysmon` event_id=1                           # I get 0 events 
```    
```
`sysmon` | eval-event_id = EventCode | table "event_id", "EventCode"      # I get "RecordID" field values in "event_id" field   
```
Any Ideas where is the problem?

**Comment by Moofeng** [comment]
I have the same problem!

**Comment by Suirand1** [comment]
I managed to find a problem!
The problem is with "source" and "sourcetype" field values.  Splunk TA addons for Sysmon and Windows logs are ingesting logs with "source = XmlWinEventLog:Microsoft-Windows-Sysmon/Operational" and "sourcetype = xmlwineventlog"
Therefore "props.conf" config is incorect for this setup since by default it takes "sourcetype" value not "source". You need to change props.conf for any of those 2 solutions below:
1. `[source::XmlWinEventLog:Microsoft-Windows-Sysmon/Operational]`
2. `[xmlwineventlog]`

P.S. spend too much time for debuging this. It would be very nice if APP could find this error or report about it.

**Comment by zwar77** [comment]
This fixed some issues I was having - I too noticed the evals were not applying but had assumed it was for other reasons and had actually completely glossed over the fact that the source needs to be spelled out and the two had been reversed.  This saved me a ton of time and effort.  I was actually re-writing most of the saved searches and found your post, thank you for finding this fix!!!

**Comment by OutpostSecurity** [comment]
Great find! I double checked this and submitted a pull request to fix it.

**Comment by olafhartong** [comment]
Thanks for flagging and fixing it guys
