### ISSUE TITLE
Unbalanced quote in T1003 Credential Dumping - Registry

### ISSUE THREAD

**Issue by afxmac** [olafhartong/ThreatHunting#61]
The search misses a quote after RestrictedRemoteSamEventThrottelingWindow before the NOT.

This leads to the following error in the Splunk log:
08-12-2020 01:00:00.788 +0200 ERROR SavedSplunker - savedsearch_id="nobody;ThreatHunting;[T1003] Credential Dumping - Registry" Unknown search command 't1003'.

After that was fixed, I am greeted with 
Could not load lookup=LOOKUP-sysmoneventcode.
when trying to execute that saved search explicitly in a search Window.

ThreatHunting App 1.4.4 from Splunkbase, Splunk 8.0.4.1.
I actually found two sysmon event code files in the app:
sysmoneventcode.csv and sysmoneventcodes.csv, but no lookup definition for them.

**Comment by OutpostSecurity** [comment]
I submitted a pull request to address the missing double quote, great catch. It also looks like the lookups should be better as well.

**Comment by olafhartong** [comment]
Thanks for flagging and fixing it guys
