### ISSUE TITLE
($exclude_technique$) AND ($exclude_host_fqdn$) Need to be removed to work

### ISSUE THREAD

**Issue by kucster** [olafhartong/ThreatHunting#63]
I've been playing with your great app and am stuck as to why to get any query to run I need to remove ($exclude_technique$) AND ($exclude_host_fqdn$). I'm rather new to Splunk but I've tried to review your code and can't quite find the culprit.
On my ThreatHunting about page everything shows up as installed. Also when I remove these values everything starts working but I think I will need them as I do need to exclude some items.
Thanks for your help
Sean

**Comment by OutpostSecurity** [comment]
Those are tokens set from the dashboard. could you post the search that does not work and then the search that does? might help narrow down how it is working in your environment.

**Comment by kucster** [comment]
Thank you for your help. It is not so much the search but the issue is the dashboard. I've attached a pic, on the left is the dashboard unmodified and the right is the modified. The modified code is below, I've pretty much just removed the ($exclude_technique$) AND ($exclude_host_fqdn$) references. 
![ThreatHunt-Issue](https://user-images.githubusercontent.com/33095768/96148388-36cb1080-0ed6-11eb-87a7-8af77bfa32e0.png)
`<form>
  <label>Threat Hunting trigger overview Copy</label>
  <fieldset submitButton="false" autoRun="true">
    <input type="time" token="time_picker">
      <label>Time range</label>
      <default>
        <earliest>-7d@d</earliest>
        <latest>now</latest>
      </default>
    </input>
    <input type="multiselect" token="exclude_technique" searchWhenChanged="true">
      <label>Exclude Technique</label>
      <fieldForLabel>mitre_technique_id</fieldForLabel>
      <fieldForValue>mitre_technique_id</fieldForValue>
      <search>
        <query>index=threathunting 
| stats count by mitre_technique_id 
| sort -count</query>
        <earliest>$time_picker.earliest$</earliest>
        <latest>$time_picker.latest$</latest>
      </search>
      <delimiter> AND </delimiter>
      <valuePrefix>mitre_technique_id!="</valuePrefix>
      <valueSuffix>"</valueSuffix>
      <choice value="none">None</choice>
      <default>none</default>
    </input>
    <input type="multiselect" token="exclude_host_fqdn" searchWhenChanged="true">
      <label>Exclude host</label>
      <fieldForLabel>host_fqdn</fieldForLabel>
      <fieldForValue>host_fqdn</fieldForValue>
      <search>
        <query>index=threathunting 
| stats count by host_fqdn 
| sort -count</query>
        <earliest>$time_picker.earliest$</earliest>
        <latest>$time_picker.latest$</latest>
      </search>
      <delimiter> AND </delimiter>
      <choice value="none">None</choice>
      <default>none</default>
      <valuePrefix>host_fqdn!="</valuePrefix>
      <valueSuffix>"</valueSuffix>
    </input>
  </fieldset>
  <row>
    <panel>
      <single>
        <title>Initial Access</title>
        <search>
          <query>index=threathunting mitre_category="*Initial_Access*" 
| timechart span=24h count(mitre_category) | appendpipe [stats count | where count=0]</query>
          <earliest>$time_picker.earliest$</earliest>
          <latest>$time_picker.latest$</latest>
          <sampleRatio>1</sampleRatio>
        </search>
        <option name="colorBy">value</option>
        <option name="colorMode">none</option>
        <option name="drilldown">all</option>
        <option name="height">125</option>
        <option name="rangeColors">["0x000","0xd93f3c"]</option>
        <option name="rangeValues">[0]</option>
        <option name="refresh.display">progressbar</option>
        <option name="showSparkline">1</option>
        <option name="showTrendIndicator">1</option>
        <option name="trendDisplayMode">absolute</option>
        <option name="unitPosition">after</option>
        <option name="useColors">1</option>
        <drilldown>
          <link target="_blank">
            <![CDATA[/app/ThreatHunting/mitre_attack_overview?form.mitre_category=*Initial_Access*&earliest=$earliest$&latest=$latest$]]>
          </link>
        </drilldown>
      </single>
    </panel>
    <panel>
      <single>
        <title>Execution</title>
        <search>
          <query>index=threathunting mitre_category="*Execution*" 
| timechart span=24h count(mitre_category) | appendpipe [stats count | where count=0]</query>
          <earliest>$time_picker.earliest$</earliest>
          <latest>$time_picker.latest$</latest>
          <sampleRatio>1</sampleRatio>
        </search>
        <option name="colorBy">value</option>
        <option name="colorMode">none</option>
        <option name="drilldown">all</option>
        <option name="height">125</option>
        <option name="rangeColors">["0x000","0xff2e45"]</option>
        <option name="rangeValues">[0]</option>
        <option name="refresh.display">progressbar</option>
        <option name="unitPosition">after</option>
        <option name="useColors">1</option>
        <drilldown>
          <link target="_blank">
            <![CDATA[/app/ThreatHunting/mitre_attack_overview?form.mitre_category=*Execution*&earliest=$earliest$&latest=$latest$]]>
          </link>
        </drilldown>
      </single>
    </panel>
    <panel>
      <single>
        <title>Persistence</title>
        <search>
          <query>index=threathunting mitre_category="*Persistence*" 
| timechart span=24h count(mitre_category) | appendpipe [stats count | where count=0]</query>
          <earliest>$time_picker.earliest$</earliest>
          <latest>$time_picker.latest$</latest>
          <sampleRatio>1</sampleRatio>
        </search>
        <option name="colorBy">value</option>
        <option name="colorMode">none</option>
        <option name="drilldown">all</option>
        <option name="height">125</option>
        <option name="rangeColors">["0x000","0xff4785"]</option>
        <option name="rangeValues">[0]</option>
        <option name="refresh.display">progressbar</option>
        <option name="unitPosition">after</option>
        <option name="useColors">1</option>
        <drilldown>
          <link target="_blank">
            <![CDATA[/app/ThreatHunting/mitre_attack_overview?form.mitre_category=*Persistence*&earliest=$earliest$&latest=$latest$]]>
          </link>
        </drilldown>
      </single>
    </panel>
    <panel>
      <single>
        <title>Privilege Escalation</title>
        <search>
          <query>index=threathunting mitre_category="*Privilege_Escalation*"  
| timechart span=24h count(mitre_category) | appendpipe [stats count | where count=0]</query>
          <earliest>$time_picker.earliest$</earliest>
          <latest>$time_picker.latest$</latest>
          <sampleRatio>1</sampleRatio>
        </search>
        <option name="colorBy">value</option>
        <option name="colorMode">none</option>
        <option name="drilldown">all</option>
        <option name="height">125</option>
        <option name="rangeColors">["0x000","0xff8041"]</option>
        <option name="rangeValues">[0]</option>
        <option name="refresh.display">progressbar</option>
        <option name="unitPosition">after</option>
        <option name="useColors">1</option>
        <drilldown>
          <link target="_blank">
            <![CDATA[/app/ThreatHunting/mitre_attack_overview?form.mitre_category=*Privilege_Escalation*&earliest=$earliest$&latest=$latest$]]>
          </link>
        </drilldown>
      </single>
    </panel>
    <panel>
      <single>
        <title>Defense Evasion</title>
        <search>
          <query>index=threathunting mitre_category="*Defense_Evasion*"  
| timechart span=24h count(mitre_category) | appendpipe [stats count | where count=0]</query>
          <earliest>$time_picker.earliest$</earliest>
          <latest>$time_picker.latest$</latest>
          <sampleRatio>1</sampleRatio>
        </search>
        <option name="colorBy">value</option>
        <option name="colorMode">none</option>
        <option name="drilldown">all</option>
        <option name="height">125</option>
        <option name="rangeColors">["0x000","0xffaf00"]</option>
        <option name="rangeValues">[0]</option>
        <option name="refresh.display">progressbar</option>
        <option name="showTrendIndicator">1</option>
        <option name="trendDisplayMode">absolute</option>
        <option name="unitPosition">after</option>
        <option name="useColors">1</option>
        <drilldown>
          <link target="_blank">
            <![CDATA[/app/ThreatHunting/mitre_attack_overview?form.mitre_category=*Defense_Evasion*&earliest=$earliest$&latest=$latest$]]>
          </link>
        </drilldown>
      </single>
    </panel>
    <panel>
      <single>
        <title>Credential Access</title>
        <search>
          <query>index=threathunting mitre_category="*Credential_Access*"  
| timechart span=24h count(mitre_category) | appendpipe [stats count | where count=0]</query>
          <earliest>$time_picker.earliest$</earliest>
          <latest>$time_picker.latest$</latest>
          <sampleRatio>1</sampleRatio>
        </search>
        <option name="colorBy">value</option>
        <option name="colorMode">none</option>
        <option name="drilldown">all</option>
        <option name="height">125</option>
        <option name="rangeColors">["0x000","0xffd300"]</option>
        <option name="rangeValues">[0]</option>
        <option name="refresh.display">progressbar</option>
        <option name="unitPosition">after</option>
        <option name="useColors">1</option>
        <drilldown>
          <link target="_blank">
            <![CDATA[/app/ThreatHunting/mitre_attack_overview?form.mitre_category=*Credential_Access*&earliest=$earliest$&latest=$latest$]]>
          </link>
        </drilldown>
      </single>
    </panel>
    <panel>
      <single>
        <title>Discovery</title>
        <search>
          <query>index=threathunting mitre_category="*Discovery*" 
| timechart span=24h count(mitre_category) | appendpipe [stats count | where count=0]</query>
          <earliest>$time_picker.earliest$</earliest>
          <latest>$time_picker.latest$</latest>
          <sampleRatio>1</sampleRatio>
        </search>
        <option name="colorBy">value</option>
        <option name="colorMode">none</option>
        <option name="drilldown">all</option>
        <option name="height">125</option>
        <option name="rangeColors">["0x000","0xabc530"]</option>
        <option name="rangeValues">[0]</option>
        <option name="refresh.display">progressbar</option>
        <option name="unitPosition">after</option>
        <option name="useColors">1</option>
        <drilldown>
          <link target="_blank">
            <![CDATA[/app/ThreatHunting/mitre_attack_overview?form.mitre_category=*Discovery*&earliest=$earliest$&latest=$latest$]]>
          </link>
        </drilldown>
      </single>
    </panel>
    <panel>
      <single>
        <title>Lateral Movement</title>
        <search>
          <query>index=threathunting mitre_category="*Lateral_Movement*" 
| timechart span=24h count(mitre_category) | appendpipe [stats count | where count=0]</query>
          <earliest>$time_picker.earliest$</earliest>
          <latest>$time_picker.latest$</latest>
          <sampleRatio>1</sampleRatio>
        </search>
        <option name="colorBy">value</option>
        <option name="colorMode">none</option>
        <option name="drilldown">all</option>
        <option name="height">125</option>
        <option name="rangeColors">["0x000","0x01c26d"]</option>
        <option name="rangeValues">[0]</option>
        <option name="refresh.display">progressbar</option>
        <option name="trendInterval">-7d</option>
        <option name="unitPosition">after</option>
        <option name="useColors">1</option>
        <drilldown>
          <link target="_blank">
            <![CDATA[/app/ThreatHunting/mitre_attack_overview?form.mitre_category=*Lateral_Movement*&earliest=$earliest$&latest=$latest$]]>
          </link>
        </drilldown>
      </single>
    </panel>
    <panel>
      <single>
        <title>Collection</title>
        <search>
          <query>index=threathunting mitre_category="*Collection*" 
| timechart span=24h count(mitre_category) | appendpipe [stats count | where count=0]</query>
          <earliest>$time_picker.earliest$</earliest>
          <latest>$time_picker.latest$</latest>
          <sampleRatio>1</sampleRatio>
        </search>
        <option name="colorBy">value</option>
        <option name="colorMode">none</option>
        <option name="drilldown">all</option>
        <option name="height">125</option>
        <option name="rangeColors">["0x000","0x007b84"]</option>
        <option name="rangeValues">[0]</option>
        <option name="refresh.display">progressbar</option>
        <option name="unitPosition">after</option>
        <option name="useColors">1</option>
        <drilldown>
          <link target="_blank">
            <![CDATA[/app/ThreatHunting/mitre_attack_overview?form.mitre_category=*Collection*&earliest=$earliest$&latest=$latest$]]>
          </link>
        </drilldown>
      </single>
    </panel>
    <panel>
      <single>
        <title>Command &amp; Control</title>
        <search>
          <query>index=threathunting mitre_category="*Command_and_Control*"  
| timechart span=24h count(mitre_category) | appendpipe [stats count | where count=0]</query>
          <earliest>$time_picker.earliest$</earliest>
          <latest>$time_picker.latest$</latest>
          <sampleRatio>1</sampleRatio>
        </search>
        <option name="colorBy">value</option>
        <option name="colorMode">none</option>
        <option name="drilldown">all</option>
        <option name="height">125</option>
        <option name="rangeColors">["0x000","0x075190"]</option>
        <option name="rangeValues">[0]</option>
        <option name="refresh.display">progressbar</option>
        <option name="showTrendIndicator">1</option>
        <option name="trendDisplayMode">absolute</option>
        <option name="unitPosition">after</option>
        <option name="useColors">1</option>
        <drilldown>
          <link target="_blank">
            <![CDATA[/app/ThreatHunting/mitre_attack_overview?form.mitre_category=*Command_and_Control*&earliest=$earliest$&latest=$latest$]]>
          </link>
        </drilldown>
      </single>
    </panel>
    <panel>
      <single>
        <title>Exfiltration</title>
        <search>
          <query>index=threathunting mitre_category="*Exfiltration*"  
| timechart span=24h count(mitre_category) | appendpipe [stats count | where count=0]</query>
          <earliest>$time_picker.earliest$</earliest>
          <latest>$time_picker.latest$</latest>
          <sampleRatio>1</sampleRatio>
        </search>
        <option name="colorBy">value</option>
        <option name="colorMode">none</option>
        <option name="drilldown">all</option>
        <option name="height">125</option>
        <option name="rangeColors">["0x000","0x86308c"]</option>
        <option name="rangeValues">[0]</option>
        <option name="refresh.display">progressbar</option>
        <option name="unitPosition">after</option>
        <option name="useColors">1</option>
        <drilldown>
          <link target="_blank">
            <![CDATA[/app/ThreatHunting/mitre_attack_overview?form.mitre_category=*Exfiltration*&earliest=$earliest$&latest=$latest$]]>
          </link>
        </drilldown>
      </single>
    </panel>
  </row>
  <row>
    <panel>
      <title>Top triggered techniques in the selected timeframe</title>
      <table>
        <search>
          <query>index="threathunting" 
| stats count by mitre_technique_id, mitre_technique, mitre_category
| sort -count</query>
          <earliest>$time_picker.earliest$</earliest>
          <latest>$time_picker.latest$</latest>
        </search>
        <option name="count">10</option>
        <option name="dataOverlayMode">highlow</option>
        <option name="drilldown">cell</option>
        <option name="percentagesRow">false</option>
        <option name="totalsRow">false</option>
        <drilldown>
          <link target="_blank">
            <![CDATA[/app/ThreatHunting/mitre_attack_overview?form.mitre_technique_id=$row.mitre_technique_id$&form.time_picker.earliest=$time_picker.earliest$&form.time_picker.latest=$time_picker.latest$]]>
          </link>
        </drilldown>
      </table>
    </panel>
    <panel>
      <title>Top triggered host_fqdns in the selected timeframe</title>
      <table>
        <search>
          <query>index="threathunting"  
| stats count by host_fqdn
| sort -count</query>
          <earliest>$time_picker.earliest$</earliest>
          <latest>$time_picker.latest$</latest>
        </search>
        <option name="count">10</option>
        <option name="dataOverlayMode">heatmap</option>
        <option name="drilldown">cell</option>
        <option name="percentagesRow">false</option>
        <option name="refresh.display">progressbar</option>
        <option name="totalsRow">false</option>
        <drilldown>
          <link target="_blank">
            <![CDATA[/app/ThreatHunting/computer_drilldown?form.computer=$row.host_fqdn$&form.time_picker.earliest=$time_picker.earliest$&form.time_picker.latest=$time_picker.latest$]]>
          </link>
        </drilldown>
      </table>
    </panel>
    <panel>
      <title>Top triggered users by host_fqdns in the selected timeframe</title>
      <table>
        <search>
          <query>index="threathunting"  
| stats count by user_name, host_fqdn
| sort -count</query>
          <earliest>$time_picker.earliest$</earliest>
          <latest>$time_picker.latest$</latest>
        </search>
        <option name="count">10</option>
        <option name="dataOverlayMode">heatmap</option>
        <option name="drilldown">cell</option>
        <option name="percentagesRow">false</option>
        <option name="refresh.display">progressbar</option>
        <option name="totalsRow">false</option>
        <drilldown>
          <link target="_blank">
            <![CDATA[/app/ThreatHunting/user_drilldown?form.user_name=$row.user_name$&form.time_picker.earliest=$time_picker.earliest$&form.time_picker.latest=$time_picker.latest$]]>
          </link>
        </drilldown>
      </table>
    </panel>
  </row>
  <row>
    <panel>
      <title>Activity by time per day</title>
      <chart>
        <search>
          <query>index=threathunting 
| stats count by _time, mitre_category 
| timechart span=15m sum(count) by mitre_category useother=false</query>
          <earliest>$time_picker.earliest$</earliest>
          <latest>$time_picker.latest$</latest>
        </search>
        <option name="charting.axisY.abbreviation">auto</option>
        <option name="charting.axisY.scale">log</option>
        <option name="charting.chart">line</option>
        <option name="charting.chart.nullValueMode">zero</option>
        <option name="charting.chart.showDataLabels">none</option>
        <option name="charting.drilldown">none</option>
        <option name="charting.layout.splitSeries">0</option>
        <option name="charting.legend.placement">right</option>
        <option name="refresh.display">progressbar</option>
        <option name="charting.legend.labels">[Initial_Access,Execution,Persistence,Privilege_Escalation,Defense_Evasion,Credential_Access,Discovery,Lateral_Movement,Collection,Command_and_Control,Exfiltration,Impact]</option>
        <option name="charting.seriesColors">[0xd8031a,0xff2e45,0xff4785,0xff8041,0xffaf00,0xffd300,0xabc530,0x01c26d,0x007b84,0x075190,0x86308c,0x482569]</option>
      </chart>
    </panel>
  </row>
</form>`

**Comment by OutpostSecurity** [comment]
so I think the input fields are mis-named, The search is expecting exclud_technique and exclude_host_fqdn and I think they are called mitre_technique_id and host_fqdn. Edit the dashboard and then edit those inputs and ensure the Token fields are correct Attached is a screenshot of the exclude host field where the Token field is correctly set. Let me know if those are correct and it is still not working.
![Edit-ExcludeHost](https://user-images.githubusercontent.com/72515718/96167762-7816ec80-0ee5-11eb-971f-a64684eef708.PNG)

**Comment by kucster** [comment]
Thank you for your continued help, I've looked at the values and I think they are correct, see below
![image](https://user-images.githubusercontent.com/33095768/96172503-8caeb100-0ef4-11eb-9ae6-1310c7dafc5a.png)

**Comment by OutpostSecurity** [comment]
Weird ok, not sure where to look, I cannot re-create the issue. If it works to just remove those token references then go for it.

**Comment by kucster** [comment]
Will do, thank you for trying
