### ISSUE TITLE
Not an Issue: Step by Step Guide to Install/Configure 

### ISSUE THREAD

**Issue by Kirtar22** [olafhartong/ThreatHunting#8]
Hi Olaf, 

I have written an article to show - how to install & configure the ThreatHunting App. This might be useful to people out there who are trying out this app. I am uploading it here as people might get easier to find this article here. It is up to you if you want to keep it here or somehwere else or not required at all. 

https://www.linkedin.com/pulse/attckized-splunk-kirtar-oza-cissp-cisa-ms-/

**Comment by olafhartong** [comment]
Thanks for the nice writeup!

**Comment by zhjygit** [comment]
> Hi Olaf,
> 
> I have written an article to show - how to install & configure the ThreatHunting App. This might be useful to people out there who are trying out this app. I am uploading it here as people might get easier to find this article here. It is up to you if you want to keep it here or somehwere else or not required at all.
> 
> https://www.linkedin.com/pulse/attckized-splunk-kirtar-oza-cissp-cisa-ms-/

This link is out of service.
My sysmon has the log of id 3, however, my threathunting dashboard is empty.
