### ISSUE TITLE
Invalid eval expression for 'EVAL-target_process_name'

### ISSUE THREAD

**Issue by Suirand1** [olafhartong/ThreatHunting#83]
I am getting some warnings in splunkd.log every half an hour.
`CalcFieldProcessor - Invalid eval expression for 'EVAL-target_process_name' in stanza [source::XmlWinEventLog:Microsoft-Windows-Sysmon/Operational]: The operator at ',replace(TargetImage,"(.*\\\)(?=.*(\.\w*)$|(\w+)$)",""),1==1,"")' is invalid.`

**Comment by Suirand1** [comment]
I did modified `props.conf `
```
- EVAL-target_process_name = case(EventCode=="6","System",EventCode=="8" OR EventCode=="10"),replace(TargetImage,"(.*\\\)(?=.*(\.\w*)$|(\w+)$)",""),1==1,"")    
+ EVAL-target_process_name = case(EventCode=="6","System",EventCode=="8" OR EventCode=="10",replace(TargetImage,"(.*\\\)(?=.*(\.\w*)$|(\w+)$)",""),1==1,"")
```
error is gone now

**Comment by olafhartong** [comment]
thanks ( very late) I fixed it!
