### ISSUE TITLE
Invalid eval expression - EVAL-target_process_name

### ISSUE THREAD

**Issue by barrettnet** [olafhartong/ThreatHunting#86]
I've just installed v1.5.0 of the app from SplunkBase and I'm seeing errors in index=_internal saying "Invalid eval expression for 'EVAL-target_process_name` in stanza [source::WinEventLog:Microsoft-Windows-Sysmon/Operational]: The operator at .... is invalid."

Looking at props.conf - I can see two instances of the line:
EVAL-target_process_name = <case statement>

My guess is that there's an issue with the regex that the replace command is trying to use.

**Comment by barrettnet** [comment]
I've just released that this is the same as issue #83

**Comment by olafhartong** [comment]
fixed it now, thanks
