### ISSUE TITLE
[T1086] PowerShell Downloads - WinProcess 

### ISSUE THREAD

**Issue by shahrokhnik** [olafhartong/ThreatHunting#89]
Hello

This report also needs to be edited

<<<<<| eval indextime = _indextime | convert ctime(indextime) | table _time indextime, host, host_fqdnName, Account_Name, New_Process_Name, Process_Command_Line| rename Process_Command_Line as process_command_line, New_Process_Name as process_path, Account_Name as user_name mitre_category mitre_technique mitre_technique_id hunting_trigger>>>>>

must be changed to  :

| eval indextime = _indextime | convert ctime(indextime) | table _time indextime, host, host_fqdnName, Account_Name, New_Process_Name, Process_Command_Line mitre_category, mitre_technique, mitre_technique_id ,hunting_trigger | rename Process_Command_Line as process_command_line, New_Process_Name as process_path, Account_Name as user_name

**Comment by olafhartong** [comment]
fixed that, thanks !
